# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ciVDYceqfmFEdP4B3eCflozk-SWc9e7i
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files


uploaded = files.upload()

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
gender_submission = pd.read_csv('gender_submission.csv')

# Merge test with gender_submission to get 'Survived' column for analysis
test_full = pd.merge(test, gender_submission, on='PassengerId')

# Info and description
print("=== Train Dataset Info ===")
train.info()

print("\n=== Train Dataset Description ===")
display(train.describe(include='all'))

# Value counts for key columns
print("\n=== Survived Value Counts ===")
print(train['Survived'].value_counts())

print("\n=== Sex Value Counts ===")
print(train['Sex'].value_counts())

print("\n=== Embarked Value Counts ===")
print(train['Embarked'].value_counts())

# Correlation heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(train.corr(numeric_only=True), annot=True, cmap='coolwarm', linewidths=0.5)
plt.title("Correlation Heatmap")
plt.show()

# Pairplot of key numeric features
sns.pairplot(train[['Survived', 'Pclass', 'Age', 'Fare', 'SibSp', 'Parch']], hue='Survived')
plt.suptitle("Pairplot of Selected Features", y=1.02)
plt.show()

# Histogram - Age
plt.figure(figsize=(8, 5))
sns.histplot(data=train, x='Age', hue='Survived', multiple='stack', bins=30)
plt.title("Age Distribution by Survival")
plt.show()

# Boxplot - Age by Pclass
plt.figure(figsize=(8, 5))
sns.boxplot(x='Pclass', y='Age', data=train)
plt.title("Age Distribution by Pclass")
plt.show()

# Scatterplot - Fare vs Age by Survival
plt.figure(figsize=(8, 5))
sns.scatterplot(data=train, x='Age', y='Fare', hue='Survived')
plt.title("Fare vs Age by Survival")
plt.show()

# Boxplot - Fare by Pclass
plt.figure(figsize=(8, 5))
sns.boxplot(x='Pclass', y='Fare', data=train)
plt.title("Fare Distribution by Pclass")
plt.show()

summary = """
Summary of Titanic Dataset Analysis:

1. Gender: Female passengers had significantly higher survival rates than males.
2. Class: Passengers in 1st class had the best chances of survival.
3. Age: Younger passengers, especially children, survived more often.
4. Fare: Higher fare passengers generally had better chances of survival.
5. Embarked: Passengers who embarked at Cherbourg (C) had higher survival rates.
6. Family Influence: SibSp and Parch suggest some survival advantage with family.
"""
print(summary)